/*
/*I AM JUST PLAYING AROUND WITH SOME PSEUDO-CODE, DO NOT USE
 * THIS BRANCH FOR ANYTHING WHATSOEVER, IT PROBABLY DOES NOT EVEN COMPILE*/

/* pathfinding.h
 *
 *  Created on: Sep 8, 2014
 *      Author: Wiseoldman95
 */

#ifndef PATHFINDING_H_
#define PATHFINDING_H_




#endif /* PATHFINDING_H_ */
